{
 "title": "208 Office Network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "208 Forti WAN-IN Traffic",
   "type": "timeseries",
   "description": "208 office Forti WAN-IN traffic",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifAlias=\"FET\",ifIndex=\"3\",ifName=\"wan1\",instance='192.168.208.254'}[5m]) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCInOctets{ifAlias=\"CHT\",ifIndex=\"4\",ifName=\"wan2\",instance='192.168.208.254'}[5m]) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCInOctets{ifAlias=\"FET\",ifIndex=\"41\",ifName=\"wan3\", instance='192.168.208.254'}[5m]) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCInOctets{ifAlias=\"CHT\",ifIndex=\"42\",ifName=\"wan4\", instance='192.168.208.254'}[5m]) *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "208 Forti WAN-OUT Traffic",
   "type": "timeseries",
   "description": "208 office Forti WAN-OUT traffic",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{ifAlias=\"FET\",ifIndex=\"3\",ifName=\"wan1\",instance='192.168.208.254'}[5m]) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCOutOctets{ifAlias=\"CHT\",ifIndex=\"4\",ifName=\"wan2\",instance='192.168.208.254'}[5m]) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCOutOctets{ifAlias=\"FET\",ifIndex=\"41\",ifName=\"wan3\", instance='192.168.208.254'}[5m]) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCOutOctets{ifAlias=\"CHT\",ifIndex=\"42\",ifName=\"wan4\", instance='192.168.208.254'}[5m]) *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "208 PC  Traffic (Port-Channel 1)",
   "type": "timeseries",
   "description": "Cisco Core Switch for 208 MIS, SYS, NET PCs\n(不含 OT, OM)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifDescr=\"Port-channel1\", ifIndex=\"149\", ifName=\"Po1\", instance=\"192.168.208.252\", job=\"snmp\"}[5m]) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(ifHCOutOctets{ifDescr=\"Port-channel1\", ifIndex=\"149\", ifName=\"Po1\", instance=\"192.168.208.252\", job=\"snmp\"}[5m]) *8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}